## Demo to see how to load another file

- name: Demo on load another file
  hosts:
  tasks:
     - name: Print Hello world
       ansible.builtin.debug:
          msg: Hello World

     - name: Include Universe file
       ansible.builtin.include_tasks:
            file: Universe.yml